export const LOAD_ROOMS = "LOAD_ROOMS";

export const ROOMS_LOADING = "ROOMS_LOADING";

export const LOAD_USER = "LOAD_USER";

export const USER_LOADING = "USER_LOADING";

export const LOAD_ROOM_BOOKED = "LOAD_ROOM_BOOKED";

export const ROOM_BOOKED_LOADING = "ROOM_BOOKED_LOADING";

export const ROOM_DETAIL_LOADING = "ROOM_DETAIL_LOADING";

export const LOAD_ROOM_DETAIL = "LOAD_ROOM_DETAIL";